# Generated by Django 2.0 on 2019-12-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_cagetory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='cagetory',
            new_name='category',
        ),
    ]
