# Generated by Django 2.0 on 2020-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200115_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='本店价格'),
        ),
    ]
